CREATE PLUGGABLE DATABASE EMPMIS_385
ADMIN USER gl_empmisadmin_385 IDENTIFIED BY empmisadmin123
ROLES = (PDB_DBA);

ALTER PLUGGABLE DATABASE empmis_385 OPEN;

ALTER SESSION SET CONTAINER = empmis_385;

SHOW CON_NAME;
